In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.stats import skew

In [3]:
data=pd.read_csv('income.csv')

In [4]:
data

age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700

In [5]:
data.isnull().sum()

age           0
experience    0
income        0
dtype: int64

In [6]:
data.shape

(20, 3)

In [7]:
data.info

<bound method DataFrame.info of     age  experience  income
0    25           1   30450
1    30           3   35670
2    47           2   31580
3    32           5   40130
4    43          10   47830
5    51           7   41630
6    28           5   41340
7    33           4   37650
8    37           5   40250
9    39           8   45150
10   29           1   27840
11   47           9   46110
12   54           5   36720
13   51           4   34800
14   44          12   51300
15   41           6   38900
16   58          17   63600
17   23           1   30870
18   44           9   44190
19   37          10   48700>

In [8]:
data.describe()

age  experience        income
count  20.000000   20.000000     20.000000
mean   39.650000    6.200000  40735.500000
std    10.027725    4.124382   8439.797625
min    23.000000    1.000000  27840.000000
25%    31.500000    3.750000  35452.500000
50%    40.000000    5.000000  40190.000000
75%    47.000000    9.000000  45390.000000
max    58.000000   17.000000  63600.000000

In [9]:
x=data.iloc[:,:-1].values

In [10]:
x

array([[25,  1],
       [30,  3],
       [47,  2],
       [32,  5],
       [43, 10],
       [51,  7],
       [28,  5],
       [33,  4],
       [37,  5],
       [39,  8],
       [29,  1],
       [47,  9],
       [54,  5],
       [51,  4],
       [44, 12],
       [41,  6],
       [58, 17],
       [23,  1],
       [44,  9],
       [37, 10]], dtype=int64)

In [11]:
y=data.iloc[:,-1].values

In [12]:
y

array([30450, 35670, 31580, 40130, 47830, 41630, 41340, 37650, 40250,
       45150, 27840, 46110, 36720, 34800, 51300, 38900, 63600, 30870,
       44190, 48700], dtype=int64)

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=1/3,random_state=0)

In [14]:
y_train

array([34800, 47830, 31580, 41630, 51300, 45150, 37650, 63600, 46110,
       40130, 30450, 38900, 36720], dtype=int64)

In [15]:
x_train

array([[51,  4],
       [43, 10],
       [47,  2],
       [51,  7],
       [44, 12],
       [39,  8],
       [33,  4],
       [58, 17],
       [47,  9],
       [32,  5],
       [25,  1],
       [41,  6],
       [54,  5]], dtype=int64)

In [16]:
from sklearn.linear_model import LinearRegression
reg=LinearRegression()
reg.fit(x_train,y_train)

LinearRegression()

In [17]:
y_pred=reg.predict(x_test)

In [18]:
y_pred

array([46399.55877308, 34742.09205917, 49156.74719831, 38424.34497058,
       30536.37516518, 31059.83914777, 39209.54094446])

In [19]:
x_test

array([[44,  9],
       [30,  3],
       [37, 10],
       [37,  5],
       [29,  1],
       [23,  1],
       [28,  5]], dtype=int64)

In [20]:
y_test

array([44190, 35670, 48700, 40250, 27840, 30870, 41340], dtype=int64)

In [22]:
print(reg.predict([[30,3]]))

[34742.09205917]
